name: TestAndBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

      - name: Install Debian Tools
        run: apt -y install software-properties-common

      - name: Add Racket PPA
        run: add-apt-repository -y ppa:plt/racket

      - name: Install Racket
        run: apt install -y racket

      - name: Compile
        run: raco make -v meloc.rkt