name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
  runs-on: ubuntu-latest

  steps:
    - name: Run top-level unit tests
      run: racket *-test.rkt

    - name: Run type system unit tests
      run: racket type-sys/*-test.rkt
